(function(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.LumnoNewtabWallpaperCatalog = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function() {
  'use strict';
  // Photo rows are [Picsum ID, photographer, Unsplash photo ID]: landscape photos from Lorem Picsum,
  // which serves Unsplash images under the Unsplash License. Art rows are [accession number, artist,
  // title]: CC0 paintings from The Cleveland Museum of Art Open Access collection. The bundle carries
  // the credits, so a synced pick shows them on every device without asking the network.
  return Object.freeze({
    nature: [
      [28, 'Jerry Adney', '_WiFMBRT7Aw'],
      [29, 'Go Wild', 'V0yAek6BgGk'],
      [46, 'Jeffrey Kam', 'Nzw3HHsNHYU'],
      [66, 'Nicholas Swanson', 'agnhLQWqr1Q'],
      [54, 'Nicholas Swanson', 'd19by2PLaPc'],
      [69, 'Alexander Shustov', 'SITaCHf7jjg'],
      [81, 'Sander Weeteling', 'rlxZqmc6D_I'],
      [83, 'Julie Geiger', 'dYshDcTI1Js'],
      [987, 'Sebastien Gabriel', '2W5LoumSdfw'],
      [991, 'Fritz Bielmeier', 'ooJi3CJQRa8'],
      [993, 'Eric Huang', 'r75qppvP-FE'],
      [1000, 'Lukas Budimaier', '6cY-FvMlmkQ'],
      [1015, 'Alexey Topolyanskiy', '-oWyJoSqBRM'],
      [1016, 'Philippe Wuyts', '_h7aBovKia4'],
      [1018, 'Andrew Ridley', 'Kt5hRENuotI'],
      [1022, 'Vashishtha Jogi', 'bClr95glx6k'],
      [1032, 'NASA', 'E7q00J_8N7A'],
      [1002, 'NASA', '6-jTZysYY_U'],
      [1036, 'Wolfgang Lutz', 'yOujaSETXlo'],
      [1037, 'Jordan McQueen', '93g2k8D1Mi8'],
      [1043, 'Christian Joudrey', 'mWRR1xj95hg'],
      [1044, 'Steve Carter', 'Ixp4YhCKZkI'],
      [1045, 'Aleksandra Boguslawska', 'USOu_Ob9rxo'],
      [1057, 'Stefan Kunze', '_SmZSuZwkHg'],
      [110, 'Kenneth Thewissen', 'D76DklsG-5U'],
      [112, 'Zugr', 'kmF_Aq8gkp0'],
      [116, 'Anton Sulsky', 'YcfCXxo7rpc'],
      [136, 'Marcin Czerwinski', '2wugfiddtXw'],
      [191, 'Alex Talmon', '6iat9p85VnQ'],
      [184, 'Tim de Groot', 'yNGQ830uFB4'],
      [109, 'Zwaddi', 'YvYBOSiBJE8'],
      [206, 'Philipp Reiner', 'qPJ6eRAMmCM'],
      [231, 'Aleksandra Boguslawska', 'XeCvtUX-AE0'],
      [235, 'Paul E. Harrer', 'TI-B-TNYJMU'],
      [241, 'Sylwia Bartyzel', '1Cg7BQXp024'],
      [247, 'Georgia Dixon', 'wuHPFRWtDLI'],
      [251, 'Tiago Gerken', 'b7g3wVqr1gU'],
      [255, 'Jon Ottosson', 'Xg1e5bR_bL4'],
      [277, 'Taylor Leopold', 'pElM4yerF5Q'],
      [254, 'Pavel Voinov', 'adG2dX-ruJ4'],
      [278, 'Taylor Leopold', '6QQqqvq4R9A'],
      [287, 'Aleksandra Boguslawska', 'c54ZhWDLEDo'],
      [296, 'Greg Shield', 'Du30R57aCyM'],
      [327, 'Ryan Schroeder', 'Gg7uKdHFb_c'],
      [324, 'Sonja Langford', 'L_F8jAsRWtU'],
      [289, 'Jennifer Langley', 'vIqxsp0_p1g'],
      [314, 'Fré Sonneveld', '1rZcfdsjoR4'],
      [282, 'Taylor Leopold', '9dw0xLlxw1s'],
      [353, 'Forrest Cavale', 'qfmd9bu7IgA'],
      [368, 'Tyssul Patel', 'o-zOatT4kQw'],
      [377, 'Martin Staněk', '8WClaa1CmZ0'],
      [386, 'Topich', 'czfUy4ZKuJ0'],
      [393, 'Alex Talmon', 'UFskvng2OMU'],
      [406, 'Roland Batke-Mutschler', 'SmhN4FejPFs'],
      [412, 'Samuel Rohl', 'WvlS1yWAu8c'],
      [423, 'Gabriel Santiago', 'pTgTMVxQE_k'],
      [426, 'Ales Krivec', '01ZeHnK3F_4'],
      [432, 'Michael Hull', 'vuWB5mGu5wE'],
      [434, 'Ales Krivec', 'DgtRKZOOE0w'],
      [443, 'Tim Mossholder', 'p3kpqGBRPok'],
      [450, 'Tanvi Malik', 'OeC1wIsKNpk'],
      [456, 'Matteo Minelli', 'VgdFyOOu1PA'],
      [458, 'Charles S.', 'lvSDZw6V8nw'],
      [461, 'Joren Frielink', 'qgfiux6vEmc'],
      [413, 'Lukasz Szmigiel', 'Hez3-whPnNA'],
      [466, 'Caleb George', 'zZzKLzKP24o'],
      [471, 'Brownie', 'BSZ3nEZlJ3c'],
      [474, 'Casey Fyfe', 'R5S4OQpG0lE'],
      [475, 'Casey Fyfe', 'zJnpPhF4HyY'],
      [476, 'Mr. Marco', 'QP1dUyQ8WsI'],
      [478, 'Antoine Beauvillain', '0Kw44ElHN3A'],
      [479, 'Parker Gibbs', 'DOMP4KhUYHA'],
      [480, 'Drew Geraets', 'NtrxaEdbMXU'],
      [482, 'Danny Froese', 'JXkCLZhhRJg'],
      [484, 'David Marcu', 'GyALQFQ9cp4'],
      [492, 'Jason Long', 'FOeDIUwYiSw'],
      [498, 'Kim Daniel', 'JsqAqevX6lg'],
      [506, 'Jeff Sheldon', 'sD--EGHBvqw'],
      [507, 'Jeff Sheldon', 'oOFrXiz8-0A'],
      [510, 'Jeff Sheldon', '4IPe3tnBKK0'],
      [511, 'Jeff Sheldon', '9EwxGJdTJNo'],
      [519, 'Alexandr Schwarz', '2eNAQUigzI0'],
      [523, 'Harman Abiwardani', 'WLUHO9A_xik'],
      [525, 'Luca Zanon', 'aViOQZzikVs'],
      [542, 'Crucifix Jean-Luc', '19tQv51x4-A'],
      [543, 'Ali Inay', 'rHv6C-WTOls'],
      [547, 'Tomasz Paciorek', 'rMwCJs4Pcw0'],
      [553, 'Rula Sibai', 'nIkuMWT4Imc'],
      [557, 'Daniel Beilinson', 'eiqJBh7eHDU'],
      [558, 'Ales Krivec', '58zgsq3c63g'],
      [559, 'Ali Inay', 'yNaGxHqjOuw'],
      [560, 'Ales Krivec', '4k-U1Wp2d00'],
      [562, 'Casey Fyfe', '6Rf6EjvdiN4'],
      [563, 'Bec Brown', '7RIm0GqvvkM'],
      [565, 'René Reichelt', 'HzaT5l4Fzqc'],
      [666, 'Jason Ortego', 'buF62ewDLcQ'],
      [667, 'Joshua Sortino', 'XMcoTHgNcQA'],
      [676, 'Drew Patrick Miller', 'B7mIW-x3g9s'],
      [549, 'Artur Pokusin', 'paNkUbhQj3Q'],
      [678, 'Samuel Zeller', 'YN_JWPDYVoM'],
      [681, 'Axel  Antas-Bergkvist', 'OAVRFaEo8qE'],
      [683, 'ahmadreza sajadi', '55xd_uiUYEE'],
      [684, 'Lee Roylland', 'dfZbts6B4yw'],
      [688, 'Benjamin Sloth Lindgreen', 'a_xa7RUKzdc'],
      [699, 'Biegun Wschodni', 'vD3L-rN_qNw'],
      [702, 'Dominik Schröder', '9PCmMdc4Crw'],
      [704, 'Ståle Grut', 'NUgw97CVdAk'],
      [724, 'Nelly Volkovich', 'ZSMgNjYrHRM'],
      [730, 'Ryan Pohanic', 'W3V2tQAZxPA'],
      [731, 'Rob Bye', '61XW8CMNX6A'],
      [741, 'Garrett Carroll', '5iPhUVPYWsw'],
      [767, 'Sébastien Marchand', 'EeEx8zpOESA'],
      [727, 'Devan Freeman', 'HrUbyeQvL_w'],
      [779, 'John Kutcher', 'UIf9YO7LsuE'],
      [780, 'Amy Zhang', 'CNzh2A9_jwE'],
      [791, 'Daniela Cuevas', 't7YycgAoVSw'],
      [794, 'Lauren Coleman', 'shy0cEi7h1o'],
      [795, 'Micah. H', 'aRZvsaPw57g'],
      [807, 'Tiago Aguiar', 'FtVQIQ9rDFI'],
      [809, 'Namphuong Van', 'sP4UZnpSiN4'],
      [810, 'Luís Perdigão', '5QyPh6O9tfw'],
      [814, 'Ales Krivec', 'duoMdMm3aY0'],
      [825, 'Michael Hull', 'UdvXJ95Yqt8'],
      [784, 'Genta Mochizawa', 'cVEfUcl6xCo'],
      [830, 'Luca Zanon', 'X0OoHrPvgXE'],
      [831, 'Luke Pamer', 'TjEjUqGHjcw'],
      [866, 'Samuel Zeller', '9RqA6tnT0gA'],
      [872, 'Brandon Lam', 'Dd_7xDCuuUo'],
      [876, 'Carmine De Fazio', '3ytjETpQMNY'],
      [877, 'Sebastian Unrau', 'dJVU4jXV1Q8'],
      [879, 'Nick Scheerbart', 'xFjAftU8lMY'],
      [880, 'Fred Viljoen', '6LkxufmApSk'],
      [884, 'thomas shellberg', '7gZEY7tY9C4'],
      [894, 'Paula Porto', 'Fma1wE_zIf8'],
      [902, 'Nitish Meena', 'RbbdzZBKRDY'],
      [903, 'Greg Rakozy', 'oMpAz-DN-9I'],
      [905, 'Caitlin Wynne', '94sVs1D3Vvw'],
      [910, 'Sudarshan Bhat', 'jgLTHYKnd5Q'],
      [915, 'McDobbie Hu', '24tsXm7qGQE'],
      [916, 'Larry Chen', 'Nte-4RiRfwU'],
      [918, 'David Marcu', 'CaQ_KITtnVY'],
      [919, 'Jon Ottosson', 'JU2MgHOHDsw'],
      [921, 'Eutah Mizushima', 'OWwK_0_EnxY'],
      [923, 'Sebastian Unrau', 'CoD2Q92UaEg'],
      [924, 'Jakub Sejkora', 'utqJcneoFjo'],
      [927, 'Cosmic Timetraveler', 'HthjuB6VkRM'],
      [929, 'Tiago Muraro', '1kEHpwZdmtc'],
      [932, 'Vadim Sherbakov', 'NQSWvyVRIJk'],
      [933, 'Gian-Reto Tarnutzer', 'rZsqmXfM3qQ'],
      [944, 'Tim Swaan', 'eOpewngf68w'],
      [957, 'Mike Petrucci', 'kluhXsuW7Is'],
      [943, 'Paul Earle', 'l98YXp1X8dA'],
      [960, 'Paulo Simões Mendes', 'V8YzvXKLwDw'],
      [961, 'Sven Scheuermeier', 'VNseEaTt9w4'],
      [964, 'Jon Ottosson', 'YD1uvthZwg4'],
      [966, 'Alberto Restifo', 'kKrfPaKgE1c'],
      [971, 'Natasha Vasiljeva', 'pRQ_G-un4xs'],
      [974, 'Greg Rakozy', '0LU4vO5iFpM'],
      [980, 'Ales Krivec', 'OmelL9tVVno'],
      [984, 'Sylvain Guiheneuc', 'hIMdKs_0cSE'],
      [967, 'NASA', 'NuE8Nu3otjo']
    ],
    water: [
      [47, 'Christopher Sardegna', 'uDUiRS8YroY'],
      [51, 'Ireneuilia', 'knYQ6arClBE'],
      [68, 'Cristian Moscoso', '2SfRAWkinpU'],
      [74, 'Isaak Dury', 'YhZbnxqtooM'],
      [990, 'Joseph Barrientos', 'UklXbPE-Hos'],
      [1019, 'Patrick Fore', 'V6s1cmE39XM'],
      [1035, 'Jared Erondu', 'j4PaE7E2_Ws'],
      [1039, 'Andrew Coelho', 'VB-w_3dnyvI'],
      [1041, 'Tim Marshall', 'yEOCA6oiVqg'],
      [1050, 'Joseph Barrientos', 'xcC5ozHk_N8'],
      [1051, 'Ales Krivec', 'HkTMcmlMOUQ'],
      [1052, 'Annie Spratt', 'x8R2oSWZRSE'],
      [1053, 'Anna Popović', 'x7HJdJZqplo'],
      [1061, 'Rob Bye', 'Kc7xqFTtcc4'],
      [128, 'Matteo Minelli', 'hlnucYOsL-c'],
      [144, 'Mouly Kumar', 'TuOiIpkIea8'],
      [154, 'Christopher Sardegna', 'x_jTtMOOMd4'],
      [199, 'Beto Galetto', 'RL0l7Zk5PxU'],
      [215, 'Paula Borowska', '04paG2PxKGs'],
      [218, 'Monika Majkowska', 'Nq8LdWC7HnM'],
      [270, 'Victoria Alexander', 'TXG9VLN1J9U'],
      [271, 'Fré Sonneveld', 'Bpb6yvtkpEY'],
      [280, 'Jay Wennington', 'yIDqQ15KgRI'],
      [295, 'Olivia Henry', '-_rYK0egLWE'],
      [323, 'Paweł Wojciechowski', 'QYAojSRu82c'],
      [350, 'Forrest Cavale', '17x5rTAAvXM'],
      [362, 'Ry Van', '2UbJtgQp8VQ'],
      [372, 'Gabriel Santiago', 'KWkMiUIxcD0'],
      [374, 'Ma. Alejandra', 'TDahcrcPhhA'],
      [381, 'Nick West', '4M-5WBrG5-c'],
      [384, 'Griffin Keller', '-mNvCsNlsSE'],
      [404, 'Cole Patrick', 'H28ODcp4EUk'],
      [421, 'Ruxandra Mateiu', '9Gmf3HPHK8o'],
      [440, 'Artur Pokusin', '0nv-h04oPhM'],
      [477, 'Jasper van der Meij', 'Xo3uIN_Q1Y0'],
      [481, 'Dustin Scarpitti', 'RdF3apSExR0'],
      [483, 'Paulo Simões Mendes', 'hrcRtexM7M0'],
      [485, 'David Marcu', 'DNXWtB33WWE'],
      [501, 'davide ragusa', 'QbDkhVZ80To'],
      [509, 'Jeff Sheldon', 'SdSc4sWVMRU'],
      [516, 'Owen Walters', '8C-TxFyk6UE'],
      [521, 'Christian Holzinger', 'lqQlmcPt9Qg'],
      [609, 'Jeremy Cai', 'mnF75FoPBWY'],
      [612, 'Justin Leibow', 'GkKJ56oZ_30'],
      [675, 'Barn Images', 'hBYzBU1xP6s'],
      [689, 'Tim Mossholder', 'P3ek4SMx_kc'],
      [715, 'Leah Tardivel', 'v8-AqxWvb6A'],
      [716, 'Matthew Kosloski', 'BT_BUEwjeQg'],
      [717, 'David Marcu', 'oyrtK2hJqBY'],
      [732, 'Dominik Schröder', 'ivieBAESVWM'],
      [756, 'Sebastien Gabriel', 'FxU8KV7psMY'],
      [787, 'Sebastien Gabriel', '6p6WDodvR2Y'],
      [788, 'Michael Baird', '6WLGMivmV00'],
      [846, 'Jeremy Bishop', 'l61smgU3Y7w'],
      [848, 'Stefanus Martanto Setyo Husodo', '74ytEYcOJDc'],
      [849, 'Rob Bye', 'OlZ1nWLEEgM'],
      [851, 'Tiago Aguiar', 'uXzNVOZT5no'],
      [853, 'Stephen Radford', '674bDNKmnIk'],
      [867, 'Stefanus Martanto Setyo Husodo', 'GKR1tBkmW3M'],
      [871, 'Stefan Kunze', '1-C334jLxG0'],
      [881, '贝莉儿 NG', 'bviex5lwf3s'],
      [890, 'Simon Schmitt', 'yjR69rDfivw'],
      [845, 'Rafael Leão', 'PW0-vZD0wis'],
      [896, 'Jenna Beekhuis', 'Bm0Ja6LZWl4'],
      [907, 'Pierre Bouillot', 'FRYtAMzphLs'],
      [909, 'Austin Schmid', '5Dga0T0x6GY'],
      [912, 'Clem Onojeghuo', '-YMhg0KYgVc'],
      [914, 'Viktor Jakovlev', 'mtNweauBsMQ'],
      [928, 'Jose Murillo', '7x4dOkulU9E'],
      [938, 'Cosmic Timetraveler', 'ALXBUzVcruQ'],
      [950, 'Nitish Kadam', 'L1B7G6XmG_8'],
      [969, 'Lee Miller', '_rsGm7nob3w'],
      [970, 'Darrell Cassell', 'hoCXpPUMCoE'],
      [973, 'Cameron Kirby', 'n3t4fIuVzLA']
    ],
    city: [
      [61, 'Alex', 'zMz14hsbpuU'],
      [1026, 'Dmitrii Vaccinium', 'Q47eNv_UvfM'],
      [1029, 'freddie marriage', 'utwYoEu9SU8'],
      [1031, 'Mike Wilson', 'rM7B4DheQc0'],
      [1040, 'Rachel Davis', 'tn2rBnvIl9I'],
      [1047, 'sergee bee', 'bIQiMWxX_WU'],
      [1048, 'Anthony DELANOIX', 'b5POxb2aL9o'],
      [1067, 'Kevin Young', '-icmOdYWXuQ'],
      [1075, 'Verne Ho', 'dccIfU1V1VU'],
      [1076, 'Samuel Zeller', 'WlD3vixTVUg'],
      [1078, 'Vladimir Kudinov', 'KBX9XHk266s'],
      [1081, 'Julien Moreau', '688Fna1pwOQ'],
      [122, 'Vadim Sherbakov', 'xS_RzdD5CFE'],
      [134, 'Charlie Foster', 'Osl4I3IS9Cw'],
      [142, 'Vadim Sherbakov', 'KSyemQIWwP8'],
      [188, 'Wojtek Witkowski', '1fpyA_z2woY'],
      [193, 'Vadim Sherbakov', 'd6ebY-faOO0'],
      [214, 'Kelly Sikkema', 'Ereoqdv5s48'],
      [238, 'Anders Jildén', 'yb0Qs65aZmc'],
      [249, 'Anders Jildén', 'nrLtvA05jk8'],
      [257, 'Emanuele Pinna', '3EYK2njhLxc'],
      [259, 'Namphuong Van', 'hfIheOEJp9M'],
      [274, 'Wojtek Witkowski', 'h7rOzTmGxWE'],
      [283, 'Wojtek Witkowski', 'GtxZbYMCiPY'],
      [288, 'Stockholm', 'eVBg7A07NGg'],
      [290, 'Aleksandar Vacić', 'nAZOGbSWK9o'],
      [299, 'Matthew Wiebe', 'nOhUx3tiaQQ'],
      [318, 'Louis Pellissier', 'wJ2SaSiL5FA'],
      [320, 'Danka & Peter', '3FN6tlvTjwM'],
      [322, 'Afroz Nawaf', 'dSyWD7oRns8'],
      [344, 'Alex Gindin', 'ifpBOcQlhoY'],
      [354, 'Piotr Kwiatkowski', 'MNyW4STma6g'],
      [369, 'Lou Levit', 'umcc42T8fD4'],
      [376, 'Andrew Ruiz', 'bI2j1olMXUA'],
      [391, 'Sarah Holmes', 'TlLgCqWEzUQ'],
      [392, 'Chris Brignola', 'n7n-nkadHRM'],
      [397, 'Jonas Lavoie-Levesque', 'XnuFhviCGio'],
      [398, 'Oscar Nilsson', '2aWEwBGSqR8'],
      [351, 'Rafael Fabricio', 'nKRVmvjW3rE'],
      [405, 'Daniel Robert', 'jIuKqvVK4Dg'],
      [411, 'Philipp Henzler', 'dgE3lWVyDh8'],
      [417, 'Siddharth Kothari', 'Xp8qDrxDeFI'],
      [419, 'POR7O', 'mS1pAG_bi5Y'],
      [420, 'Rob Potvin', 'VLWy8LIdzsQ'],
      [430, 'Carli Jean', 'Gk6YgzmrLgM'],
      [436, 'Lucas Theis', 'MO-30jajbrM'],
      [437, 'Bonnie Meisels', 'Y5uyOoct2pg'],
      [448, 'Gabriel Santiago', 'bIZrEK-Z_cI'],
      [441, 'David Marcu', 'JZXAr--Qdf4'],
      [503, 'Ramiro Checchi', 'BpN4qo98j-Y'],
      [524, 'Charles Forerunner', 'gapYVvUg1M8'],
      [545, 'Ryan Lum', '1ak3Z7ZmtQA'],
      [546, 'Hartmut Tobies', 'O9TEKuI1Icw'],
      [554, 'Vita Vilcina', '0G1r-Cg0zS8'],
      [629, 'davide ragusa', '1PHDS-PFtcM'],
      [690, 'David Marcu', '7dwwcdv7wc4'],
      [693, 'Rob Bye', 'bopC0sTGu-E'],
      [703, 'Alyssa Smith', 'xNZHQn6lyLk'],
      [737, 'Anthony Indraus', 'v4ZUGlrdVAA'],
      [743, 'Anthony DELANOIX', 'Aa8_X_YgrO4'],
      [764, 'Skyler Smith', 'PT1152jFqd4'],
      [799, 'Yulia Vambold', 's0ifr6qb6H0'],
      [818, 'Anthony DELANOIX', 'hv5pLutRkCI'],
      [826, 'Nick Scheerbart', 'QmemudqzrXQ'],
      [857, 'Dmitry Sytnik', 'bW2vHKCxbx4'],
      [860, 'Skyler Smith', 'ISHD1ovpJ-k'],
      [862, 'Benjamin Combs', 'bLppF5sbXPo'],
      [864, 'Lili Popper', '71cd1rWqO8M'],
      [893, 'Samuel Zeller', 'j0g8taxHZa0'],
      [945, 'Steve Richey', 'UB7YmsJTEvE'],
      [946, 'Padurariu Alexandru', '2UE1givDiPM'],
      [947, 'Anthony DELANOIX', 'vNAZubsDWMg'],
      [952, 'Noah Rosenfield', 'Za0O5DovZBc'],
      [953, 'Alexandre Perotto', 'zCevd81eJDU'],
      [972, 'Matthew Wiebe', 'VviFtDJakYk'],
      [983, 'Padurariu Alexandru', 'ZKBQmgMyf8s'],
      [985, 'Hide Obara', '2p1HOcpi14U']
    ],
    minimal: [
      [44, 'Christopher Sardegna', 'R1E6x8U83Ho'],
      [70, 'Dorothy Lin', 'OokBLPrkCNk'],
      [989, 'Paul Jarvis', 'eBDdgbM5dSo'],
      [992, 'Elliott Engelmann', 'DjlKxYFJlTc'],
      [994, 'Jonathan Bean', 'ywnnwzcdR5o'],
      [1028, 'Dikaseva', 'zvf7cZ0PC20'],
      [1055, 'Neil Thomas', '12rzbJhQ89E'],
      [1056, 'Susanne Feldt', 'SIoHky3TPeo'],
      [1064, 'Olivier Miche', 'iIg4F2IWbTM'],
      [1068, 'Padurariu Alexandru', 'iNmouRApXYM'],
      [114, 'Brian Gonzalez', 'llYg8Ni43fc'],
      [124, 'Anton Sulsky', 'fj0tFloTPGQ'],
      [130, 'Ryan Jacques', 'ywiAen4L4qA'],
      [131, 'Charlie Foster', 'yPaskTQiNjA'],
      [135, 'Yuriy Khimanin', 'o4H20aIIAt8'],
      [185, 'Tim de Groot', 'M_eB1UjE0do'],
      [198, 'Sylwia Bartyzel', 'FC9mIjVT-Yw'],
      [213, 'Kelly Sikkema', 'X7dy114KWs4'],
      [228, 'Michal Kubicek', '0AbVUUorULU'],
      [264, 'Jon Phillips', 'XsPM2CBTTpI'],
      [266, 'John Maravelakis', 'Vosp2wlY3Bs'],
      [267, 'Robin Benad', 'uLLUnacamlo'],
      [269, 'Jill Heyer', 'bbV7QzDUJus'],
      [275, 'davide ragusa', 'ATutAPqj4zw'],
      [279, 'Taylor Leopold', 'OHS0yA7OkrQ'],
      [300, 'Pavel Voinov', '2f_CnEeZsVg'],
      [313, 'Sonja Langford', '4xYgBTYC2-Q'],
      [293, 'Paul E. Harrer', 'AJqHzUbc1io'],
      [347, 'Alex Talmon', 'umq-jgTjr28'],
      [383, 'Jacob Valerio', '1tjjwmK5Q10'],
      [385, 'Griffin Keller', '7oS_26cb1Wo'],
      [387, 'Martin Dörsch', '8ZgJyLGbC7Y'],
      [427, 'James Douglas', 'LJb0yZ7UD7o'],
      [439, 'Matthew Wiebe', 'VQIbwDaqJKc'],
      [457, 'Volkan Olmez', 'ccPpd02Spe0'],
      [465, 'Paula Vermeulen', '_f2m3mEkaaU'],
      [467, 'Taylor Leopold', 'COE-CIGj8VA'],
      [468, 'Silvestri Matteo', '6-C0VRsagUw'],
      [472, 'Dustin Scarpitti', 'gR_zHJqbtzo'],
      [496, 'davide ragusa', 'mOPCiXScx08'],
      [499, 'Gabriel Santiago', 'qFabgklobRY'],
      [538, 'Julia Revitt', 'yypv2Tu-mxU'],
      [544, 'Francesco Gallarotti', '-HkuuUSY1pE'],
      [552, 'Hugo Kerr', 'Ke96snCJ1m0'],
      [677, 'davide ragusa', 'slgtMF8EjYE'],
      [705, 'Breno Machado', 'GBO4_7WymqY'],
      [723, 'Blair Fraser', 'aI1tDC8PaLM'],
      [733, 'Dominik Schröder', 'FIKD9t5_5zQ'],
      [739, 'Siyan Ren', 'jN_VbffJHlI'],
      [765, 'Grant McIver', 'pmUEwPKL5IE'],
      [769, 'Blake Richard Verdoorn', 'SbcqUQ4iEcI'],
      [774, 'Alex Wigan', '5qlegaTwZpM'],
      [796, 'Colton  Brown', 'aQoOdWdYpis'],
      [805, 'Jens Lelie', 'GUneOBRhq9w'],
      [808, 'elizabeth lies', 'YbgPWfWlvkE'],
      [813, 'Roger Burkhard', 'rlX9J28Pd9g'],
      [798, 'Aaron Burden', 'UvRMcIeXq9Y'],
      [847, 'Andrej Chudy', 'uivWDK2Ifrg'],
      [852, 'Mark Asthoff', 'Pk8t4cL2pkw'],
      [855, 'Rodion Kutsaev', 'IJ25m7fXqtk'],
      [886, 'Glen Carrie', 'p62O--o1x-U'],
      [887, 'Roman Kraft', '7sMHTVJ0OTA'],
      [888, 'Cristian Baron', 'dPFaq7RVzbQ'],
      [906, 'Andras Toth', 'E9CrQou9K0Y'],
      [913, 'Mikkel Schmidt', 'SR68yPh06As'],
      [922, 'Patrick Hendry', '37ZuGYD3JOk'],
      [925, 'Patrick Fore', 'vpAKO21abME'],
      [926, 'Harman Abiwardani', 'mU_aX6JBYmg'],
      [931, 'Paul Earle', 'xJ2tjuUHD9M'],
      [939, 'Alec Cutter', 'Sfn8f32ZIj0'],
      [942, 'Carl Nenzen Loven', 'busqfOj6i80'],
      [954, 'Todd Quackenbush', 'JJB_K8aCPU4'],
      [965, 'Liane Metzler', 'c5uShPcKLAE'],
      [986, 'Oliver & Hen Pritchard-Barrett', 'Xwk4gkiMNGc'],
      [962, 'Austin Schmid', 'PFy-3PaHT_M'],
      [941, 'Ivan Slade', 'RdyMe8KQAV0']
    ],
    art: [
      ['1980.262', 'Jean-Léon Gérôme', 'Alpine Landscape: The Handegg, Switzerland'],
      ['1935.217', 'John Henry Twachtman', 'Storm Clouds'],
      ['1951.330', 'Jean Baptiste Camille Corot', 'The Pond at the Entrance of the Woods'],
      ['1985.145', 'George Hendrik Breitner', 'Construction Site in Amsterdam'],
      ['1946.73', 'Claude Lorrain', 'Italian Landscape'],
      ['1964.371.7', 'Shen Zhou', 'The Thousand Buddha Hall and the Pagoda of the "Cloudy Cliff" Monastery, from Twelve Views of Tiger Hill, Suzhou'],
      ['2001.41.a', 'Edward H. Potthast', 'In the Surf (recto)'],
      ['2001.41.b', 'Edward H. Potthast', 'Beach Study (verso)'],
      ['1955.37.2', 'Zha Shibiao', 'Landscape Album in Various Styles: Spring Plowing'],
      ['1955.37.8', 'Zha Shibiao', 'Landscape Album in Various Styles: Landscape after Mi Fei'],
      ['1973.2', 'Salomon van Ruysdael', 'Castle on a River'],
      ['1972.326', 'Clarence Holbrook Carter', 'Lake Erie Patterns'],
      ['1948.461', 'Julius Caesar Ibbetson', 'A Storm Behind the Isle of Wight'],
      ['1955.37.6', 'Zha Shibiao', 'Landscape Album in Various Styles: Traveling in Autumn Mountains'],
      ['1955.37.9', 'Zha Shibiao', 'Landscape Album in Various Styles: Pleasure in a Mountain Brook'],
      ['1975.78', 'Georges Michel', 'Landscape Near Paris'],
      ['1942.121', 'Henry Ward Ranger', 'The Lone Sentinel'],
      ['1973.156.1', 'Maruyama Ōkyo', 'Summer Night'],
      ['1975.20', 'Worthington Whittredge', 'Landscape with Haywain'],
      ['1982.37', 'Albert Bierstadt', 'Fir Trees and Storm Clouds'],
      ['1916.1034', '', 'Greek Pirates Attacking a Turkish Vessel'],
      ['1980.245', 'Antoine Chintreuil', 'The Marl Pit at Mulcent: Evening'],
      ['1980.188.4', 'Tani Bunchō', 'Wild Geese Descending on a Sandbar, from Eight Views of Xiao-Xiang'],
      ['1980.188.1', 'Tani Bunchō', 'Mountain Market in Clearing Mist, from Eight Views of Xiao-Xiang'],
      ['1980.188.2', 'Tani Bunchō', 'Evening Snow Blending River and Sky, from Eight Views of Xiao-Xiang'],
      ['1980.188.3', 'Tani Bunchō', 'Returning Sails off a Distant Shores, from Eight Views of Xiao-Xiang'],
      ['1962.157.7', 'Mei Qing', 'Landscapes in Various Styles after Old Masters'],
      ['1968.209', 'Jasper F. Cropsey', 'Mount Washington, New Hampshire'],
      ['1923.1118', 'Homer Dodge Martin', 'Wild Coast, Newport'],
      ['1946.255', 'John Frederick Kensett', 'View near Newport'],
      ['1962.157.3', 'Mei Qing', 'Landscapes in Various Styles after Old Masters'],
      ['1962.157.9', 'Mei Qing', 'Landscapes after Various Styles of Old Masters'],
      ['1977.125', 'Célestin François Nanteuil', 'In the Forest'],
      ['2019.167', 'Yuan Yao', 'Road to Shu'],
      ['2015.518', 'Kano Motonobu', 'Landscape'],
      ['1927.387', 'George Inness', 'Durham, Connecticut'],
      ['1919.32', 'Augustin Satra', 'Niagara Falls'],
      ['1922.358', 'Victor Charreton', 'Murol in the Snow'],
      ['1955.669', 'Jasper F. Cropsey', 'Gray Day on the Esopus'],
      ['1961.228', 'William Stanley Haseltine', 'Natural Bridge, Sorrento'],
      ['1967.193.i', 'Zhang Ruoai', 'Desk Album: Flower and Bird Paintings (Gossiping Sparrows)'],
      ['1997.247.d', 'Yoshitsugu Haizan', 'Painting Three from Album of Paintings by Haizan'],
      ['1997.247.e', 'Yoshitsugu Haizan', 'Painting Four from Album of Paintings by Haizan'],
      ['1997.247.f', 'Yoshitsugu Haizan', 'Painting Five from Album of Paintings by Haizan'],
      ['1997.247.h', 'Yoshitsugu Haizan', 'Painting Seven from Album of Paintings by Haizan'],
      ['1997.247.j', 'Yoshitsugu Haizan', 'Painting Nine from Album of Paintings by Haizan'],
      ['1997.247.l', 'Yoshitsugu Haizan', 'Painting Eleven from Album of Paintings by Haizan'],
      ['1997.247.m', 'Yoshitsugu Haizan', 'Painting Twelve from Album of Paintings by Haizan'],
      ['1997.247.n', 'Yoshitsugu Haizan', 'Painting Thirteen from Album of Paintings by Haizan'],
      ['1999.210', 'John Frederick Kensett', 'View of Niagara Falls'],
      ['2008.288', 'Rafel Govertsz. Camphuysen', 'An Estuary Scene with Fisherman']
    ]
  });
});
